# 应用名称
spring:
  application:
    name: spring-boot-handle-unify

  # Unable to start LiveReload server
  # 在使用SpringBoot 热部署插件 devtools ,同时启动多个Application时，控制台会报这个警告
  # DevToolsProperties中配置了一个端口,默认是35729, 提示这个错误是端口冲突, 修改一下端口既可
  devtools:
    livereload:
      port: 35739
server:
  port: 8080


