# 应用名称
spring:
  application:
    name: spring-boot-handle-unify
  profiles:
    active: dev


  # Unable to start LiveReload server
  # 在使用SpringBoot 热部署插件 devtools ,同时启动多个Application时，控制台会报这个警告
  # DevToolsProperties中配置了一个端口,默认是35729, 提示这个错误是端口冲突, 修改一下端口既可
  devtools:
    livereload:
      port: 35739





# 日志管理
logging:
  level:
    root: info
  # 日志配置文件存放目录
  config: classpath:logback-spring.xml



